### ISSUE TITLE
GTNH 2.0.3.2 Crash when clicking on controller with multiblock visualizer

### ISSUE THREAD

**Issue by Zodiack256b** [SinTh0r4s/HydroEnergy#33]
I installed the preview version of GTNH 2.0.3.2 from the discord.

I placed the hydro dam controller down and clicked the block with the multiblock visualizer item to see how to build the multiblock. 
Doing so causes the client to crash.

I have attached the crash log for review
[crash-2022-03-03_19.43.44-client.txt](https://github.com/SinTh0r4s/HydroEnergy/files/8182395/crash-2022-03-03_19.43.44-client.txt)
.

**Comment by SinTh0r4s** [comment]
They either shipped 2.0.3.2 with the wrong version of StructureLib or they changed it once again. Either way, please ask them to resolve it. I am working full-time now and don't have any spare time.

**Comment by Dream-Master** [comment]
@Zodiack256b Tickets can be made here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues

**Comment by Dream-Master** [comment]
@Zodiack256b test with this file please
http://jenkins.usrv.eu:8080/job/HydroEnergy/61/
and report if it is fixed. Thanks
